name: Build GBA ROM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install devkitARM (via apt packages)
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make

    - name: Build GBA ROM
      run: |
        make

    - name: Upload ROM artifact
      uses: actions/upload-artifact@v4
      with:
        name: stepper-32steps-gba
        path: stepper.gba
